query($userAddress: String!) {
  nftTokens(
    orderBy: tokenId
    orderDirection: desc
    where: { userAddress: $userAddress, isBurned: false }
  ) {
    id
    userAddress
    tokenId
    liquidity
  }
}
